[package]
authors = ["Connor Slade <connor@connorcode.com>"]
edition = "2021"
name = "half-stack"
version = "0.1.0"

[dependencies]
json = {path = "../json"}
misc = {path = "../misc"}
trace = {path = "../trace"}
